theme = "autumn"

[editor]
completion-timeout = 150
end-of-line-diagnostics = "info"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-type"]
